# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomProfile',
            new_name='Profile',
        ),
    ]
