# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='to',
            new_name='where_are_you',
        ),
    ]
