# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_auto_20180521_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30)),
                ('Number_plate', models.CharField(max_length=40)),
                ('seats_available', models.IntegerField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('start', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=30)),
            ],
        ),
    ]
