# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_auto_20180527_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='Phone_number',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
