# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0005_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Driver.Car'),
        ),
    ]
