# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0005_car_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seats_available',
            field=models.IntegerField(),
        ),
    ]
