# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Driver', '0006_driver_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='users_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
