# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0009_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Venue',
        ),
    ]
