# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0010_auto_20180522_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Driver.Profile'),
        ),
    ]
