# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0011_venue_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('national_id', models.CharField(max_length=40)),
                ('Reviews', models.CharField(max_length=40)),
            ],
        ),
    ]
