# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0013_passenger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='where_to',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
